sso.login=Login with SSO
password.login=Login with password
choice.separator=Or ...
sso.user.not.found=You were authenticated, but no corresponding account was found. Please contact your administrator.
sso.idp.error=Login was not permitted by the identity provider. Please contact your administrator.
