package scot.gov.www;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.onehippo.repository.scheduling.RepositoryJob;
import org.onehippo.repository.scheduling.RepositoryJobExecutionContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import scot.gov.publishing.jcr.FeatureFlag;
import scot.gov.publishing.jcr.SessionSaver;

import javax.jcr.Node;
import javax.jcr.NodeIterator;
import javax.jcr.RepositoryException;
import javax.jcr.Session;
import javax.jcr.version.VersionException;
import javax.jcr.version.VersionManager;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Scheduled job that rewrites legacy links in {@code hippostd:html} rich-text nodes to
 * Bloomreach portable {@code hippo:facetselect} links.
 *
 * <p>Content migrated from the previous CMS may contain two forms of non-portable link:
 * <ol>
 *   <li>Absolute URLs: {@code https://www.gov.scot/some/path}</li>
 *   <li>Site-relative paths: {@code /some/path}</li>
 * </ol>
 *
 * <p>For each matching {@code href} the configured {@link LinkRewriteStrategy} is asked to
 * resolve it to a JCR {@code hippo:handle} node.  When a handle is found a
 * {@code hippo:facetselect} child node is created (or reused) on the {@code hippostd:html}
 * node and the href in the stored HTML is replaced with the facetselect node's name (the
 * handle's UUID).  The resulting link is portable: if the target document is moved within
 * the repository Bloomreach will keep the link intact.
 *
 * <p>Links that cannot be resolved are logged at DEBUG level and left unchanged.
 *
 * <p><b>Scalability</b>: the job walks the JCR content tree one top-level content area at a
 * time (news, publications, policies, …) using recursive {@link NodeIterator} traversal.
 * No large query result-set is held open; at most one level of child nodes is in memory at
 * any point.  Saves are batched via {@link SessionSaver} (batch size {@value #SAVE_BATCH_SIZE},
 * throttle delay {@value #SAVE_DELAY_MS} ms) to avoid overwhelming the repository.
 *
 * <p><b>Control flag</b> (boolean property under {@code /content/featureflags/}):
 * {@code LinkRewriteJob} — set to {@code true} to start the job.  The flag is re-checked
 * at each top-level content area boundary and every {@value #FLAG_CHECK_INTERVAL} html
 * nodes processed, so setting it to {@code false} mid-run stops the job cleanly.  The job
 * self-disables the flag on full completion.
 *
 * <p><b>Versioned nodes</b>: if modifying a {@code hippostd:html} node throws a
 * {@link VersionException} (because its parent document variant is checked in), the job
 * performs a checkout of the parent variant, applies the changes, saves, and checks the
 * variant back in.
 *
 * <p><b>Idempotency</b>: hrefs that already look like UUIDs are skipped, so re-running
 * after a partial stop will not double-rewrite any link.
 */
public class LinkRewriteJob implements RepositoryJob {

    private static final Logger LOG = LoggerFactory.getLogger(LinkRewriteJob.class);

    static final int  SAVE_BATCH_SIZE     = 100;
    static final long SAVE_DELAY_MS       = 1_000L;
    static final int  FLAG_CHECK_INTERVAL = 100;
    static final int  LOG_INTERVAL        = 1_000;

    static final String CONTENT_ROOT = "/content/documents/govscot";

    static final String HIPPOSTD_CONTENT  = "hippostd:content";
    static final String HIPPO_FACETSELECT = "hippo:facetselect";
    static final String HIPPO_DOCBASE     = "hippo:docbase";
    static final String HIPPO_FACETS      = "hippo:facets";
    static final String HIPPO_MODES       = "hippo:modes";
    static final String HIPPO_VALUES      = "hippo:values";

    static final String GOV_SCOT_PREFIX = "https://www.gov.scot/";

    private static final String[] EMPTY_STRINGS = new String[0];

    /**
     * UUID pattern: 8-4-4-4-12 hex digits.  Matches hrefs that have already been rewritten
     * to Bloomreach portable facetselect links and should not be touched again.
     */
    private static final Pattern UUID_PATTERN =
            Pattern.compile("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(#.*)?",
                    Pattern.CASE_INSENSITIVE);

    /**
     * Matches legacy index-page hrefs such as {@code /index_1}, {@code /index_2}, that were
     * generated by the old CMS as paginated index URLs.  These are always unresolvable and
     * logged with their containing node so the content can be investigated.
     */
    private static final Pattern INDEX_N_PATTERN =
            Pattern.compile(".*/index_\\d+$");

    /**
     * Matches hrefs that are safe to pass to {@link javax.jcr.Node#hasNode}: only
     * alphanumerics, hyphens, and underscores — the characters found in UUIDs and simple
     * node names.  Excludes {@code =}, {@code [}, spaces, and other characters that
     * Jackrabbit cannot parse as a JCR path segment.
     */
    private static final Pattern SIMPLE_NODE_NAME =
            Pattern.compile("[A-Za-z0-9_\\-]+");

    GovScotLinkRewriteStrategy strategy = new GovScotLinkRewriteStrategy();

    @Override
    public void execute(RepositoryJobExecutionContext context) throws RepositoryException {
        Session session = context.createSystemSession();
        try {
            FeatureFlag flag = new FeatureFlag(session, LinkRewriteJob.class.getSimpleName());
            if (!flag.isEnabled()) {
                LOG.info("LinkRewriteJob is not enabled, skipping");
                return;
            }
            doExecute(session, flag);
        } catch (Exception e) {
            LOG.error("LinkRewriteJob: unexpected error", e);
        } finally {
            session.logout();
        }
    }

    void doExecute(Session session, FeatureFlag flag) throws RepositoryException {
        SessionSaver saver = new SessionSaver(session, SAVE_BATCH_SIZE, SAVE_DELAY_MS);
        Stats stats = new Stats();

        try {
            walkContentAreas(session, saver, stats, flag);
        } catch (JobStoppedException e) {
            saver.forceSave();
            logStats(stats);
            LOG.info("LinkRewriteJob: stopped early by operator");
            return;
        } catch (RepositoryException e) {
            LOG.error("LinkRewriteJob: error during processing; saving progress before re-throwing", e);
            logStats(stats);
            saver.forceSave();
            throw e;
        }

        saver.forceSave();
        logStats(stats);
        LOG.info("LinkRewriteJob: complete");
        flag.setEnabled(false);
        session.save();
        LOG.info("LinkRewriteJob: self-disabled feature flag");
    }

    // ---- Tree walk -------------------------------------------------------------------------

    /**
     * Iterates the direct children of {@value #CONTENT_ROOT} (news, publications, policies,
     * etc.) and walks each subtree in turn.  The feature flag is checked before each area so
     * the job can be stopped on an area boundary as well as during processing.
     */
    private void walkContentAreas(Session session, SessionSaver saver, Stats stats, FeatureFlag flag)
            throws RepositoryException {
        if (!session.nodeExists(CONTENT_ROOT)) {
            LOG.warn("LinkRewriteJob: content root {} not found, aborting", CONTENT_ROOT);
            return;
        }

        NodeIterator areas = session.getNode(CONTENT_ROOT).getNodes();
        while (areas.hasNext()) {
            Node area = areas.nextNode();
            if (!area.isNodeType("hippostd:folder")) {
                continue;
            }
            if (!flag.isEnabled()) {
                throw new JobStoppedException();
            }
            LOG.info("LinkRewriteJob: starting content area {}", area.getPath());
            walkNode(area, saver, stats, flag);
            LOG.info("LinkRewriteJob: finished content area {}", area.getPath());
            logStats(stats);
        }
    }

    /**
     * Visits {@code node}: if it is a {@code hippostd:html} node it is processed for link
     * rewriting; otherwise all child nodes are visited recursively.
     *
     * <p>JCR system-namespace children ({@code jcr:*}, {@code rep:*}) and
     * {@code hippo:facetselect} nodes are skipped — the latter avoids descending into
     * child nodes that this job itself adds to html nodes.
     */
    private void walkNode(Node node, SessionSaver saver, Stats stats, FeatureFlag flag)
            throws RepositoryException {
        stats.visited++;
        stats.lastVisitedPath = node.getPath();
        logProgress(stats);

        if (node.isNodeType("hippostd:html")) {
            processHtmlNode(node, saver, stats, flag);
            return;
        }

        NodeIterator children = node.getNodes();
        while (children.hasNext()) {
            Node child = children.nextNode();
            String name = child.getName();
            if (name.startsWith("jcr:") || name.startsWith("rep:")) {
                continue;
            }
            if (child.isNodeType(HIPPO_FACETSELECT)) {
                continue;
            }
            walkNode(child, saver, stats, flag);
        }
    }

    // ---- Per-node processing ---------------------------------------------------------------

    private void processHtmlNode(Node htmlNode, SessionSaver saver, Stats stats, FeatureFlag flag)
            throws RepositoryException {
        stats.processed++;

        String html = htmlNode.getProperty(HIPPOSTD_CONTENT).getString();
        Document doc = Jsoup.parse(html);

        List<LinkReplacement> replacements = collectReplacements(htmlNode, doc, stats);
        if (replacements.isEmpty()) {
            return;
        }

        applyReplacements(htmlNode, replacements, stats);
        saver.save();
        checkStopFlag(flag, stats);
    }

    // ---- Link collection -------------------------------------------------------------------

    private List<LinkReplacement> collectReplacements(Node htmlNode, Document doc, Stats stats)
            throws RepositoryException {
        List<LinkReplacement> replacements = new ArrayList<>();
        for (Element link : doc.select("a[href]")) {
            String href = link.attr("href");
            // Hrefs that are bare names (no leading slash, no scheme) and already exist as a
            // child node of this html node are already in the correct internal format — skip
            // them completely so they don't contribute to any counts.
            if (!href.startsWith("/") && !href.contains(":") && SIMPLE_NODE_NAME.matcher(href).matches()
                    && htmlNode.hasNode(href) && htmlNode.getNode(href).isNodeType(HIPPO_FACETSELECT)) {
                LOG.debug("LinkRewriteJob: skipping href='{}' in {} — already a facetselect child node",
                        href, htmlNode.getPath());
                continue;
            }
            if (!needsRewriting(href)) {
                continue;
            }
            stats.considered++;
            Node target;
            try {
                target = strategy.findTargetNode(htmlNode.getSession(), href, htmlNode.getPath());
            } catch (RepositoryException e) {
                LOG.warn("LinkRewriteJob: error resolving href='{}' in {}, skipping", href, htmlNode.getPath(), e);
                recordUnresolvable(href, stats);
                continue;
            }
            if (target == null) {
                LOG.debug("LinkRewriteJob: cannot resolve href='{}' in {}", href, htmlNode.getPath());
                recordUnresolvable(href, stats);
                continue;
            }
            replacements.add(new LinkReplacement(href, target, strategy.lastResolutionType));
        }
        return replacements;
    }

    private static void recordUnresolvable(String href, Stats stats) {
        stats.notRewritten++;
        if (isBinariesHref(href)) {
            stats.binariesUnresolvable++;
        }
        stats.unresolvableByPrefix.merge(firstPathSegment(href), 1, Integer::sum);
    }

    private static boolean isBinariesHref(String href) {
        return href.contains("/binaries/");
    }

    /**
     * Extracts the first path segment from an href for frequency bucketing.
     * Strips any host prefix ({@code https://www.gov.scot}, etc.) first, then returns
     * the leading segment — e.g. {@code /news} for {@code /news/some-story} or
     * {@code https://www.gov.scot/news/some-story}.  Returns {@code (other)} for
     * hrefs that don't yield a recognisable first segment.
     */
    static String firstPathSegment(String href) {
        String path = href;
        // Strip scheme + host, leaving just the path
        int schemeEnd = href.indexOf("://");
        if (schemeEnd >= 0) {
            int pathStart = href.indexOf('/', schemeEnd + 3);
            if (pathStart < 0) {
                return "(other)";
            }
            path = href.substring(pathStart);
        }
        // path now starts with / (or is a bare relative path)
        String[] parts = path.split("/");
        for (String part : parts) {
            if (!part.isEmpty()) {
                return "/" + part;
            }
        }
        return "(other)";
    }

    /**
     * Returns {@code true} when {@code href} is a legacy link that should be rewritten:
     * an absolute {@code https://www.gov.scot/…} URL or a site-relative path.
     *
     * <p>Returns {@code false} for:
     * <ul>
     *   <li>Bare fragment identifiers ({@code #section})</li>
     *   <li>Any URI scheme — detected by a colon appearing before the first slash, which
     *       covers well-formed URLs ({@code http://…}), malformed ones ({@code http:}),
     *       and other schemes ({@code mailto:}, {@code tel:}, {@code javascript:}, …)</li>
     *   <li>Hrefs that already look like Bloomreach UUIDs</li>
     * </ul>
     */
    boolean needsRewriting(String href) {
        if (href == null || href.isEmpty() || href.startsWith("#")) {
            return false;
        }
        if (UUID_PATTERN.matcher(href).matches()) {
            return false;
        }
        if (href.startsWith(GOV_SCOT_PREFIX)) {
            return true;
        }
        // Reject any URI scheme: a colon before the first slash (or with no slash at all)
        // covers http://, http:, mailto:, tel:, javascript:, ftp://, etc.
        int colonPos = href.indexOf(':');
        if (colonPos >= 0) {
            int slashPos = href.indexOf('/');
            return slashPos >= 0 && colonPos >= slashPos;
        }
        return true;
    }

    // ---- Replacement application -----------------------------------------------------------

    /**
     * Applies all collected link replacements to {@code htmlNode}, handling the case where
     * the parent document variant is checked in by performing a checkout/checkin cycle on
     * the variant.
     */
    private void applyReplacements(Node htmlNode, List<LinkReplacement> replacements, Stats stats)
            throws RepositoryException {
        try {
            doApplyReplacements(htmlNode, replacements, stats);
        } catch (VersionException e) {
            LOG.trace("VersionException on {}", htmlNode.getPath(), e);
            String variantPath = htmlNode.getParent().getPath();
            LOG.trace("LinkRewriteJob: variant is checked in, using checkout/checkin for {}", variantPath);
            Session session = htmlNode.getSession();
            VersionManager vm = session.getWorkspace().getVersionManager();
            vm.checkout(variantPath);
            doApplyReplacements(htmlNode, replacements, stats);
            session.save();
            vm.checkin(variantPath);
            LOG.trace("LinkRewriteJob: checkout/checkin complete for {}", variantPath);
        }
    }

    private void doApplyReplacements(Node htmlNode, List<LinkReplacement> replacements, Stats stats)
            throws RepositoryException {
        // Re-read the current HTML in case an earlier batch already touched this node
        String html = htmlNode.getProperty(HIPPOSTD_CONTENT).getString();

        for (LinkReplacement r : replacements) {
            Node facet = ensureFacetSelect(htmlNode, r.targetHandle);
            String facetName = facet.getName();
            html = html.replace("\"" + r.originalHref + "\"", "\"" + facetName + "\"");
            stats.rewritten++;
            incrementTypeCounter(r.resolutionType, stats);
            LOG.info("LinkRewriteJob: rewrote href='{}' -> facet='{}' in {}",
                    r.originalHref, facetName, htmlNode.getPath());
        }

        htmlNode.setProperty(HIPPOSTD_CONTENT, html);
    }

    /**
     * Returns an existing {@code hippo:facetselect} child of {@code htmlNode} whose
     * {@code hippo:docbase} already points to {@code targetHandle}, or creates a new one.
     *
     * <p>The node is named with the handle's UUID, matching the convention the CMS uses when
     * editors insert internal links through the link picker.
     */
    private Node ensureFacetSelect(Node htmlNode, Node targetHandle) throws RepositoryException {
        String uuid = targetHandle.getIdentifier();

        NodeIterator children = htmlNode.getNodes();
        while (children.hasNext()) {
            Node child = children.nextNode();
            if (HIPPO_FACETSELECT.equals(child.getPrimaryNodeType().getName())
                    && uuid.equals(child.getProperty(HIPPO_DOCBASE).getString())) {
                return child;
            }
        }

        Node facet = htmlNode.addNode(uuid, HIPPO_FACETSELECT);
        facet.setProperty(HIPPO_DOCBASE, uuid);
        facet.setProperty(HIPPO_FACETS, EMPTY_STRINGS);
        facet.setProperty(HIPPO_MODES, EMPTY_STRINGS);
        facet.setProperty(HIPPO_VALUES, EMPTY_STRINGS);
        return facet;
    }

    // ---- Flow control ----------------------------------------------------------------------

    private void checkStopFlag(FeatureFlag flag, Stats stats) {
        if (stats.processed > 0 && stats.processed % FLAG_CHECK_INTERVAL == 0 && !flag.isEnabled()) {
            throw new JobStoppedException();
        }
    }

    private static void incrementTypeCounter(GovScotLinkRewriteStrategy.ResolutionType type, Stats stats) {
        switch (type) {
            case NEWS:         stats.rewrittenByNews++;         break;
            case PUBLICATIONS: stats.rewrittenByPublications++; break;
            case ISBN:         stats.rewrittenByIsbn++;         break;
            case PATH:         stats.rewrittenByPath++;         break;
            case TOPIC:        stats.rewrittenByTopic++;        break;
            case REDIRECT:     stats.rewrittenByRedirect++;     break;
        }
    }

    private void logProgress(Stats stats) {
        if (stats.visited % LOG_INTERVAL == 0) {
            logStats(stats);
        }
    }

    private void logStats(Stats stats) {
        LOG.info("LinkRewriteJob: htmlNodes={}, considered={}, rewritten={}, notRewritten={} (binaries={}) lastPath={}",
                stats.processed, stats.considered, stats.rewritten,
                stats.notRewritten, stats.binariesUnresolvable, stats.lastVisitedPath);
        LOG.info("LinkRewriteJob: rewritten by type: news={}, publications={}, isbn={}, path={}, topic={}, redirect={}",
                stats.rewrittenByNews, stats.rewrittenByPublications, stats.rewrittenByIsbn,
                stats.rewrittenByPath, stats.rewrittenByTopic, stats.rewrittenByRedirect);
        if (!stats.unresolvableByPrefix.isEmpty()) {
            String breakdown = stats.unresolvableByPrefix.entrySet().stream()
                    .sorted(Map.Entry.<String, Integer>comparingByValue().reversed())
                    .limit(25)
                    .map(e -> "  " + e.getKey() + "=" + e.getValue())
                    .collect(Collectors.joining("\n"));
            LOG.info("LinkRewriteJob: not rewritten by first path segment (top 25):\n{}", breakdown);
        }
    }

    // ---- Inner types -----------------------------------------------------------------------

    private static class Stats {
        int    visited              = 0;    // every node entered during the tree walk
        int    processed            = 0;    // hippostd:html nodes examined
        int    considered           = 0;    // links where needsRewriting() returned true
        int    rewritten            = 0;    // links successfully rewritten to facetselects
        int    notRewritten         = 0;    // potential links whose target could not be found
        int    binariesUnresolvable = 0;    // notRewritten links whose path starts with /binaries/
        // per-type rewrite counts (sum equals rewritten)
        int    rewrittenByNews          = 0;
        int    rewrittenByPublications  = 0;
        int    rewrittenByIsbn          = 0;
        int    rewrittenByPath          = 0;
        int    rewrittenByTopic         = 0;
        int    rewrittenByRedirect      = 0;
        String lastVisitedPath      = null; // path of the most recently visited node
        /** Frequency of unresolvable hrefs keyed by their first path segment (e.g. {@code /news}). */
        Map<String, Integer> unresolvableByPrefix = new HashMap<>();
    }

    private static class LinkReplacement {
        final String originalHref;
        final Node   targetHandle;
        final GovScotLinkRewriteStrategy.ResolutionType resolutionType;

        LinkReplacement(String originalHref, Node targetHandle,
                        GovScotLinkRewriteStrategy.ResolutionType resolutionType) {
            this.originalHref   = originalHref;
            this.targetHandle   = targetHandle;
            this.resolutionType = resolutionType;
        }
    }

    private static class JobStoppedException extends RuntimeException {
        JobStoppedException() {
            super("LinkRewriteJob stopped by operator (flag disabled)");
        }
    }
}
