definitions:
  config:
    /hippo:configuration/hippo:groups/publication-editors:
      hipposys:members:  [publicationuser]
    /hippo:configuration/hippo:groups/publication-extra-folder-options:
      hipposys:members: [publicationuser]
