sso.login=Login with Okta
password.login=Login with password
choice.separator=Or
sso.user.not.found=Access is not allowed for this user. Please contact website@gov.scot
sso.idp.error=Login was not allowed. Please contact digital-publishing@gov.scot
sso.callback.error=An error occurred. Please try again or contact digital-publishing@gov.scot
